
version: '3.3'
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: netflix_mysql8
    ports:
      - 33061:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super_complex_password
      MYSQL_DATABASE:  netflix_db
      MYSQL_USER: netflix_user
      MYSQL_PASSWORD: complex_password
volumes:
  db_data: {}